appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
xunleiServerHttp:
  port: 2345
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts:
- hostPath: /mnt/extras/something
  mountPath: /mnt/extras
  readOnly: true
gpuConfiguration: {}
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: cnk3x/xunlei
  tag: latest
updateStrategy: Recreate
